<div class="card">
    <div class="card-body pb-0 pt-0">
        <table class="table data_table table-responsive-lg">
            <thead>
                <tr>
                    <th class="th-lg">Logo</th>
                    <th class="th-lg">Name</th>
                    <th class="th-lg">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php
                if (is_object($partners)){
                    $partner=$partners;
                    ?>
                        <tr>
                            <td><img src="<?=$partner->__get('logo')?>" style="height: 60px;"></td>
                            <td><?=$partner->__get('name')?></td>
                            <td>
                                <a href="<?=$helper->getHost()?>dashboard/partner/?type=edit&id=<?=$partner->__get('id')?>" class="btn btn-sm btn-primary px-3 mr-2"><i class="fa fa-edit"></i></a>
                                <a href="<?=$helper->getHost()?>dashboard/partner/?type=delete&id=<?=$partner->__get('id')?>" class="btn btn-sm btn-danger px-3 partner-remove" data-title="<?=$partner->__get('name')?>"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                        <?php
                }
                else {
                    foreach ($partners as $key => $partner) {
                        ?>
                        <tr>
                            <td><img src="<?=$partner->__get('logo')?>" style="height: 60px;"></td>
                            <td><?=$partner->__get('name')?></td>
                            <td>
                                <a href="<?=$helper->getHost()?>dashboard/partner/?type=edit&id=<?=$partner->__get('id')?>" class="btn btn-sm btn-primary px-3 mr-2"><i class="fa fa-edit"></i></a>
                                <a href="<?=$helper->getHost()?>dashboard/partner/?type=delete&id=<?=$partner->__get('id')?>" class="btn btn-sm btn-danger px-3 partner-remove" data-title="<?=$partner->__get('name')?>"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                        <?php
                    }
                }
                ?>
            </tbody>
        </table>
    </div>
</div>




<div class="fixed-action-btn clearfix d-none d-xl-block" style="bottom: 45px; right: 24px;">
    <a href="<?=$helper->getHost()?>dashboard/partner/?type=add" class="btn-floating btn-lg red">
        <i class="fa fa-pencil"></i>
    </a>
</div>
<script>
    $('.partner-remove').on('click', function(e){
        e.preventDefault();
        $('#window-modal .modal-title').html('<span class="text-danger">Partner löschen</span>');
        $('#window-modal .modal-body').html('<p class="mb-0 mt-0">Sind Sie sich sicher, dass der Partner <b>"' + $(this).attr('data-title') + '"</b> unwiderruflich gelöscht werden soll?</p>');
        $('#window-modal .modal-footer').attr({'style':'display:block;'}).html('<a href="' + $(this).attr('href') + '" class="btn btn-danger btn-sm">Löschen</a><button type="button" class="btn btn-default btn-sm float-right" data-dismiss="modal">Schließen</button>');
        $('#window-modal').modal({
            show:true,
            backdrop:'static'
        });
    });
</script>