<?php
if (!is_array($login_error) && isset($login_error)){
    echo '<div class="alert alert-danger" role="alert">'.$login_error.'</div>';
}
?>
<form class="form-horizontal" action="<?=$helper->getHost()?>dashboard/login/" method="POST">
    <?php
    if (isset($login_error['email']) && $login_error['email']!==''){
        foreach ($login_error['email'] as $error) {
            echo '<p class="text-danger" style="font-size: small;margin-left: 2.5rem;margin-bottom: 0px;">'.$error.'</p>';
        }
    }
    ?>
    <div class="form-group">
        <label for="email">E-Mail</label> 
        <input type="email" name="email" class="form-control" id="email" placeholder="Geben Sie E-Mail">
    </div>
    <?php
    if (isset($login_error['passord']) && $login_error['passord']!==''){
        foreach ($login_error['passord'] as $error) {
            echo '<p class="text-danger" style="font-size: small;margin-left: 2.5rem;margin-bottom: 0px;">'.$error.'</p>';
        }
    }
    ?>
    <div class="form-group">
        <label for="password">Passwort</label> 
        <input type="password" name="password" class="form-control" id="password" placeholder="Geben Sie Passwort">
    </div>
    <div class="form-group row m-t-20">
        <div class="col-sm-6">
            <a href="<?=$helper->getHost()?>dashboard/reset/"><i class="mdi mdi-lock"></i> Passwort vergessen?</a>
        </div>
        <div class="col-sm-6 text-right">
            <button class="btn btn-primary w-md waves-effect waves-light" type="submit">Anmelden</button>
        </div>
    </div>
</form>
