<!-- <div class="alert alert-success" role="alert">Enter your Email and instructions will be sent to you!</div> -->
<form class="form-horizontal" action="index.html">
    <div class="form-group">
        <label for="useremail">Email</label> 
        <input type="email" class="form-control" id="useremail" placeholder="Enter email">
    </div>
    <div class="form-group row m-t-20 mb-0">
        <div class="col-12 text-right">
            <button class="btn btn-primary w-md waves-effect waves-light" type="submit">Reset</button>
        </div>
    </div>
</form>