<section id="main" class="row" style="margin: 0;width:100%;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="error-template" style="text-align: center;">
                    <h1>
                        Oops!</h1>
                    <h2>
                        404 Not Found</h2>
                    <div class="error-details">
                        Entschuldigung, es ist ein Fehler aufgetreten. Die angeforderte Seite wurde nicht gefunden!
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
