<?php
$info=$helper->MetaToArray($info);
?>
<form method="POST">
    <div class="row">
        <div class="col-xl-9 col-md-6 mb-4">
            <div class="card mb-4 processing d-none">
                <div class="card-body">
                    <div id="progress_convert" class="progress primary-color-dark mb-0 mt-o">
                        <div class="indeterminate"></div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="md-form mt-0 mb-0">
                        <input type="text" name="title" class="form-control" placeholder="Titel hier eingeben" value="<?=$post->__get('title')?>">
                    </div>
                    <p id="permalink" class="mb-0 mt-2">Permalink: <a href="<?=$post->__get('guid')?>" target="_blank"><?=$post->__get('guid')?></a> <button id="edit_permalink" type="button" class="btn btn-sm btn-default d-none">Bearbeiten</button></p>
                    <input type="text" name="name" class="d-none" value="<?=$post->__get('name')?>">
                    <input type="text" name="guid" class="d-none" value="<?=$post->__get('guid')?>">
                </div>
            </div>
           
            <div class="card mt-4">
                <div class="card-body">
                    <div id="editor" style="height: 300px;font-size: 1.1em; font-family: 'Ubuntu';"><?=$post->__get('content')?></div>
                    <textarea name="content" class="d-none" type="text"></textarea>
                </div>
            </div>
            <div class="card mt-4">
                <div class="card-body">
                    <label>Stichwörter</label>
                    <div class="md-form mt-0 mb-0">
                        <div class="chips chips-placeholder"></div>
                        <textarea type="text" name="keywords" class="d-none"></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card">
                <div class="card-body">
                    <p class="text-center h6-responsive">Veröffentlichen</p>
                    <!--<label>Status</label>-->
                    <select name="status" class="mdb-select colorful-select dropdown-primary">
                        <option value="publish"<?=$post->__get('status')==='publish'?' selected':''?>>Veröffentlicht</option>
                        <option value="draft"<?=$post->__get('status')==='draft'?' selected':''?>>Entwurf</option>
                    </select>
                </div>
                <div class="card-footer">
                    <!-- <a href="<?=$helper->getHost()?>preview/?post_id=<?=$post->__get('id')?>" target="_blank" class="btn btn-cyan">Vorschau</a> -->
                    <button type="submit" class="btn btn-primary float-right">Aktualisieren</button>
                </div>
            </div>

            <div class="card mt-4">
                <div class="card-body">
                    <p class="text-center h6-responsive">Beitragsbild</p>
                    <?php
                    if ($post->__get('img')!==null && $post->__get('img')!==''){
                        ?>
                    <img src="<?=$post->__get('img')?>" id="post_img" style="width: 100%;" class="img-fluid img-thumbnail mt-3">
                        <?php
                    }
                    ?>
                    <div id="uploadImage" class="md-form mb-0">
                        <div class="file-field">
                            <div class="btn btn-primary btn-sm float-left">
                                <span>Datei wählen</span>
                                <input id="fileupload_img" name="header_img" type="file">
                                <input name="file_name_img" type="text" class="d-none">
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text" placeholder="">
                            </div>
                        </div>
                    </div>
                    <div id="progress_img" class="progress d-none" style="margin-top: 20px;">
                        <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>

                    <table id="files_img" style="margin-top:0px;" class="files table d-none mb-0 table-responsive-lg table-borderless"></table>     
                    <?php
                    if ($post->__get('img')!==null && $post->__get('img')!==''){
                        ?>
                    <div class="form-check mr-3 pl-0 mt-3">
                        <input name="no_header_img" class="form-check-input" type="checkbox" id="no_header_img">
                        <label class="form-check-label" for="no_header_img">Kein Beitragsbild</label>
                    </div>
                        <?php
                    }
                    ?>
                </div>
            </div>
            <div class="card mt-4">
                <div class="card-body">
                    <p class="text-center h6-responsive">Seiten-Attribute</p>
                    <div>
                        <label>Eltern</label>
                        <select name="parent" class="mdb-select colorful-select dropdown-primary">
                            <option value="0">Hauptseite (keine Übergeordnete)</option>
                            <?php
                            //$page_liste=$helper->getPageListe();
                            if (is_object($page_liste)){
                                $page=$page_liste;
                                if ($post->__get('id')!==$page->__get('id')):
                                ?>
                            <option value="<?=$page->__get('id')?>"><?=$page->__get('title')?></option>
                                <?php
                                endif;
                            }
                            else {
                                foreach ($page_liste as $key => $page) {
                                    if ($post->__get('id')!==$page->__get('id')):
                                    ?>
                                <option value="<?=$page->__get('id')?>"><?=$page->__get('title')?></option>
                                    <?php
                                    endif;
                                }
                            }
                            ?>
                        </select>
                    </div>
                    <div>
                        <label>Layout</label>
                        <select name="layout" class="mdb-select colorful-select dropdown-primary">
                            <option <?=$info['layout']==='layout'?'selected':''?> value="layout">Standard-Layout</option>
                            <option <?=$info['layout']==='landing'?'selected':''?> value="landing">Landing-Layout</option>
                            <option <?=$info['layout']==='right-sidebar'?'selected':''?> value="right-sidebar">Rechte Sidebar</option>
                            <option <?=$info['layout']==='left-sidebar'?'selected':''?> value="left-sidebar">Linke Sidebar</option>
                            <option <?=$info['layout']==='no-sidebar'?'selected':''?> value="no-sidebar">Volle Breite</option>
                        </select>
                    </div>
                    <div>
                        <label>Kommentare</label>
                        <select name="comment_status" class="mdb-select colorful-select dropdown-primary">
                            <option value="open" <?=$post->__get('comment_status')==='open'?'selected':''?>>Erlaubt</option>
                            <option value="close" <?=$post->__get('comment_status')==='close'?'selected':''?>>Nicht Erlaubt</option>
                        </select>
                    </div>
                    <div class="d-none">
                        <label>Reihenfolge</label>
                        <div class="md-form mt-0 mb-0">
                            <input type="number" name="menu_order" class="form-control" placeholder="Reihenfolge" value="0">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">
    
    var options = {
        theme: 'snow',
        modules : {
            toolbar: [
                [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
                [{ 'font': [] }],
                ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
                ['blockquote', 'code-block'],
                [{ 'list': 'ordered'}, { 'list': 'bullet' }],
                [{ 'script': 'sub'}, { 'script': 'super' }],      // superscript/subscript
                [{ 'indent': '-1'}, { 'indent': '+1' }],          // outdent/indent
                [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
                [{ 'align': [] }],
                ['link', 'image', 'video'],
                ['clean']
            ]
        }
    };
    
    var quill = new Quill('#editor', options);

//    var editorElement = CKEDITOR.replace('editor');
        
    // Für Beitrag oder Seite erstellen
    $('input[name=title]').on('change', function(){
        var link = $('input[name=title]').val();
        var url='<?=$helper->getHost()?>service/';          
        //var parent=$('select[name=parent]').val();
                
        link=link.toLowerCase();
        link=link.replace(/ /g, "_");
        
        var request=$.ajax({
            url:'<?=$helper->getHost()?>api/checkName/',
            type:'POST',
            dataType:'JSON',
            data: {"name":link, 'page_type':'service'},
            success: function(result){
                $('#permalink a').attr('href',url+result.name+'/');
                $('#permalink a').html(url+result.name+'/');
                $('input[name=name]').val(result.name);
                $('input[name=guid]').val(url+result.name+'/');
                $('#permalink').removeClass('d-none');
            },
            error: function(xhr, status, error){
                console.log(xhr);
                alert(status + ': ' + error);
            }
        });
    });    
    
    $('.chips-placeholder').material_chip({
        placeholder: '+ Stichwort',
        secondaryPlaceholder: '+ Stichwort',
        <?='data: '.$post->__get('keywords').','?>
    });
        
    
    $(document).on('submit', 'form', function(){
        var content = document.querySelector('textarea[name=content]');
        content.textContent = quill.container.firstChild.innerHTML;
        $('textarea[name=keywords]').val(JSON.stringify($('.chips').material_chip('data')));
        $('form').serialize();
        return true;
    });
</script>

<!-- Image Beitrag -->
<script>
    /*jslint unparam: true, regexp: true */
    /*global window, $ */
    $(function () {
        'use strict';
        // Change this to the location of your server-side upload handler:
        var removeButton = $('<button/>')
                .addClass('btn btn-danger btn-sm removeButton_img')
                .html('<i class="fa fa-trash"></i>')
                .attr('data-type','DELETE')
                .css({"float":"right"});

        $('#fileupload_img').fileupload({
            url: '/api/uploadImage/',
            dataType: 'json',
            autoUpload: true,
            acceptFileTypes: /(\.|\/)(jpe?g|bmp|png)$/i,
//                                    maxFileSize: 300000000,
            previewCrop: true,
            sequentialUploads: true,
            complete : function (data, e){
                console.log(data);
                $('#progress_img .progress-bar').css('width','0%');
                $('#progress_img').addClass('d-none');
            }
        }).on('fileuploadstart', function (e) {
            $('#progress_img .progress-bar').css('width','0%');
            $('#progress_img').removeClass('d-none');
            $('#uploadImage').addClass('d-none');
        }).on('fileuploadprogress', function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('#progress_img .progress-bar').css(
                'width',
                progress + '%'
            );
        }).on('fileuploaddone', function (e, data) {
            data.context = $('#files_img');
            $.each(data.result.header_img, function (index, file) {
                if (file.error){
                    $('#window-modal .modal-title').html('<span class="text-danger">Ein Fehler ist aufgetreten</span>');
                    $('#window-modal .modal-body').html(file.error);
                    $('#window-modal .modal-footer').html('<button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">'+Close()+'</button>');
                    $('#window-modal').modal({
                        show:true,
                        backdrop:'static'
                    });
                }
                else {
                    var fileListe={};
                    var node = $('<div/>').attr({'class':'<?=$post->__get('page_type')==='video'?'mt-2 col-xl-6 col-lg-6':'mt-3 pl-0 pr-0 col-xl-12 col-lg-12'?> col-md-12 col-sm-12 col-12'});
                        node.append($('<img/>').attr({'src':'/source/upload/tmp_image/medium/'+file.name, 'class':'img-fluid img-thumbnail mb-2'}));
                    if (!index) {
                        node.append($('<div/>').attr({'class':'pb-0'}).append(removeButton.clone(true).data(data).attr('data-file', file.name)));
                    }
                    node.appendTo(data.context);

                    fileListe[file.name]=file.url;
                    $('#file_liste_img').val(JSON.stringify(fileListe));
                    $('#files_img').removeClass('d-none');
                    
                    $('input[name=file_name_img]').val(file.name);
                    $('#post_img').addClass('d-none');
                }
            });
            $('#progress_img').addClass('d-none');
        }).on('fileuploadfail', function (e, data) {
            $.each(data.files, function (index) {
                var error = $('<span class="text-danger"/>').text('File upload failed.');
                $(data.context.children()[index])
                    .append('<br>')
                    .append(error);
            });
        }).on('fileuploadprocessfail', function (e, data) {
            var errorMsg;

            console.log(data);

            if (data.files[data.index].error=="File type not allowed"){
                errorMsg="Dateityp nicht erlaubt.";
            }
            else if (data.files[data.index].error=="File is too large"){
                errorMsg="Datei ist zu groß.";
            }
            else if (data.files[data.index].error=="Maximum number of files exceeded"){
                errorMsg="Maximale Anzahl der Dateien überschritten.";
            }
            else if (data.files[data.index].error=="File is too small"){
                errorMsg="Die Datei ist zu klein.";
            }
            else if (data.files[data.index].error=="Uploaded bytes exceed file size"){
                errorMsg="Hochgeladene Bytes überschreiten die Dateigröße.";
            }
            else {
                errorMsg="Ein Fehler ist aufgetreten.";
            }

            $('#window-modal .modal-title').html('<span class="text-danger">Ein Fehler ist aufgetreten</span>');
            $('#window-modal .modal-body').html(errorMsg);
            $('#window-modal .modal-footer').html('<button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Schließen</button>');
            $('#window-modal').modal({
                show:true,
                backdrop:'static'
            });
        }).prop('disabled', !$.support.fileInput)
            .parent().addClass($.support.fileInput ? undefined : 'disabled');
    });
    
    
    $(document).on('click', '.removeButton_img', function(e){
        e.preventDefault();
        var url = '/api/uploadImage/',
            $this=$(this);
        $.ajax({
            url: url+'?header_im='+$(this).attr('data-file'),
            dataType: 'json',
            type: 'DELETE',
            success: function(data, xhr){
                var $td=$this.parent(),
                    $tr=$td.parent();
                var fileListe={};
                $.each(data, function (index, result) {
                    if (result){
                        $($tr).remove();
                        delete fileListe[index];
                        $('#file_liste_img').val(JSON.stringify(fileListe));
                    }
                    $('#files_img').addClass('d-none');
                });
                $('#uploadImage').removeClass('d-none');
                $('#post_img').removeClass('d-none');
            }
        });

    });    
</script>