<section class="mb-3">
    <div class="row">
        
        <style>
            tbody tr th{
                width:250px;
                font-size: 1rem;
                /*vertical-align: text-top;*/
                vertical-align: top;
                padding: 20px 10px 20px 0;
                line-height: 1.3;
            }
            .mdb-select{
                width: max-content;
                width: -moz-fit-content;
            }
        </style>

        <?php
        if(isset($success) && $success===true){
            ?>
            <div class="col-lg-12 col-md-12">
                <div class="alert alert-success alert-dismissible fade show w-100" role="alert">
                    Einstellungen gespeichert.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <?php
        }
        ?>
        <div class="col-lg-12 col-md-12 mb-4">
            <div class="card">
                <div class="card-body pt-0 px-0">
                    <div class="card-body pb-0">
                        <h5 class="card-title">
                            <i class="fa fa-cogs mr-2"></i> Einstellungen › E-Mail
                        </h5>
                        <form method="post" class="mx-2 mt-4 mb-0 md-form">
                            <table class="form" style="width:100%;">
                                <tbody>
                                    <tr id="transport">
                                        <th scope="row">
                                            Transport
                                        </th>
                                        <td>
                                            <select name="transport" class="mdb-select">
                                                <option value="smtp" <?=$setting['transport']==='smtp'?'selected':''?>>SMTP</option>
                                                <option value="sendmail" <?=$setting['transport']==='sendmail'?'selected':''?>>Senmail</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr id="host">
                                        <th scope="row">
                                            Postausgang Server
                                        </th>
                                        <td>
                                            <input name="host" type="text" value="<?=$setting['host']?>" class="form-control">
                                        </td>
                                    </tr>
                                    <tr id="port">
                                        <th scope="row">
                                            Postausgang Port
                                        </th>
                                        <td>
                                            <input name="port" type="number" value="<?=$setting['port']?>" class="form-control">
                                        </td>
                                    </tr>
                                    <tr id="user">
                                        <th scope="row">
                                            Benutzername
                                        </th>
                                        <td> 
                                            <input name="user" type="text" value="<?=$setting['user']?>" class="form-control">
                                        </td>
                                    </tr>
                                    <tr id="password">
                                        <th scope="row">
                                            Passwort
                                        </th>
                                        <td> 
                                            <input name="password" type="password" value="<?=$setting['password']?>" class="form-control">
                                        </td>
                                    </tr>
                                    <tr id="mail_from">
                                        <th scope="row">
                                            Senden als
                                        </th>
                                        <td> 
                                            <input name="mail_from" type="email" value="<?=$setting['mail_from']?>" class="form-control">
                                        </td>
                                    </tr>
                                    <tr id="ssl">
                                        <th scope="row">
                                            Verschlüsselung
                                        </th>
                                        <td>
                                            <select name="ssl" class="mdb-select">
                                                <option value="ssl" <?=$setting['ssl']==='ssl'?'selected':''?>>SSL</option>
                                                <option value="tls" <?=$setting['ssl']==='tls'?'selected':''?>>TLS</option>
                                            </select>
                                        </td>
                                    </tr>
                                    
                                </tbody>
                            </table>
                            <button type="submit" class="btn btn-primary mt-4">Änderungen speichern</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
$(document).ready(function(){
    if ($("select[name=transport]").val()==='smtp'){
        $("#mail_from").addClass('d-none');
    }
    else {
        $("#host").addClass('d-none');
        $("#port").addClass('d-none');
        $("#user").addClass('d-none');
        $("#password").addClass('d-none');
        $("#ssl").addClass('d-none');
    }
});


$("select[name=transport]").on('change', function(){
    console.log($(this).val());
    if ($(this).val()==='smtp'){
        $("#host").removeClass('d-none');
        $("#port").removeClass('d-none');
        $("#user").removeClass('d-none');
        $("#password").removeClass('d-none');
        $("#ssl").removeClass('d-none');
        $("#mail_from").addClass('d-none');
    }
    else {
        $("#mail_from").removeClass('d-none');
        $("#host").addClass('d-none');
        $("#port").addClass('d-none');
        $("#user").addClass('d-none');
        $("#password").addClass('d-none');
        $("#ssl").addClass('d-none');
    }
});

</script>