<section class="mb-3">
    <div class="row">
        <style>
            tbody tr th{
                width:250px;
                font-size: 1rem;
                /*vertical-align: text-top;*/
                vertical-align: top;
                padding: 20px 10px 20px 0;
                line-height: 1.3;
            }
        </style>
        <?php
        if(isset($success) && $success===true){
            ?>
            <div class="col-lg-12 col-md-12">
                <div class="alert alert-success alert-dismissible fade show w-100" role="alert">
                    Einstellungen gespeichert.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <?php
        }
        ?>
        <div class="col-lg-12 col-md-12 mb-4">
            <div class="card">
                <div class="card-body pt-0 px-0">
                    <div class="card-body pb-0">
                        <h5 class="card-title">
                            <i class="fa fa-cogs mr-2"></i> Einstellungen › Medien
                        </h5>
                        <form method="post" class="mx-2 mt-4 mb-0 md-form">
                            <p>Die unten aufgeführten Größen bestimmen die maximalen Abmessungen in Pixel, die beim Hinzufügen von Bildern zur Mediathek verwendet werden.</p>
                            <table class="form">
                                <tbody>
                                    <tr>
                                        <th scope="row">Vorschaubilder</th>
                                        <td>
                                            <table class="form">
                                                <tbody>
                                                    <tr>
                                                        <th scope="row" style="width:150px;">Breite</th>
                                                        <td>
                                                            <input name="thumbnail_size_w" type="number" step="1" min="0" id="thumbnail_size_w" value="<?=$setting['thumbnail_size_w']?>" class="form-control">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row" style="width:150px;">Höhe</th>
                                                        <td>
                                                            <input name="thumbnail_size_h" type="number" step="1" min="0" id="thumbnail_size_h" value="<?=$setting['thumbnail_size_h']?>" class="form-control">
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>                                            
                                            <div class="form-check pl-0 pb-3">
                                                <input name="thumbnail_crop" type="checkbox" id="thumbnail_crop" value="1" <?=$setting['thumbnail_crop']==="0"?"":"checked"?>>
                                                <label for="thumbnail_crop" style="color:#212529;">Das Vorschaubild auf die exakte Größe beschneiden (Vorschaubilder sind normalerweise proportional)</label>
                                            </div>
                                            
                                        </td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Mittelgroß</th>
                                        <td>
                                            <table class="form">
                                                <tbody>
                                                    <tr>
                                                        <th scope="row" style="width:150px;">Maximale Breite</th>
                                                        <td>
                                                            <input name="medium_size_w" type="number" step="1" min="0" id="medium_size_w" value="<?=$setting['medium_size_w']?>" class="form-control">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row" style="width:150px;">Maximale Höhe</th>
                                                        <td>
                                                            <input name="medium_size_h" type="number" step="1" min="0" id="medium_size_h" value="<?=$setting['medium_size_h']?>" class="form-control">
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Groß</th>
                                        <td>
                                            <table class="form">
                                                <tbody>
                                                    <tr>
                                                        <th scope="row" style="width:150px;">Maximale Breite</th>
                                                        <td>
                                                            <input name="large_size_w" type="number" step="1" min="0" id="large_size_w" value="<?=$setting['large_size_w']?>" class="form-control">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row" style="width:150px;">Maximale Höhe</th>
                                                        <td>
                                                            <input name="large_size_h" type="number" step="1" min="0" id="large_size_h" value="<?=$setting['large_size_h']?>" class="form-control">
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <button type="submit" class="btn btn-primary mt-4">Änderungen speichern</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>