<section class="mb-3">
    <div class="row">
        <style>
            tbody tr th{
                width:250px;
                font-size: 1rem;
                /*vertical-align: text-top;*/
                vertical-align: top;
                padding: 20px 10px 20px 0;
                line-height: 1.3;
            }
        </style>
        <?php
        if(isset($success) && $success===true){
            ?>
            <div class="col-lg-12 col-md-12">
                <div class="alert alert-success alert-dismissible fade show w-100" role="alert">
                    Einstellungen gespeichert.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <?php
        }
        ?>
        <div class="col-lg-12 col-md-12 mb-4">
            <div class="card">
                <div class="card-body pt-0 px-0">
                    <div class="card-body pb-0">
                        <h5 class="card-title">
                            <i class="fa fa-cogs mr-2"></i> Einstellungen › Lesen
                        </h5>
                        <?=var_dump($response)?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>