<form method="POST">
    <!-- <div class="card">
        <div class="card-body p-0">
            <ul class="nav nav-tabs nav-tabs-custom nav-justified" role="tablist">
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="ui-tabs-accordions.html#home2" role="tab" aria-selected="false">
                        <span class="d-block d-sm-none"><i class="fas fa-home"></i></span> <span class="d-none d-sm-block">Bild</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="ui-tabs-accordions.html#profile2" role="tab" aria-selected="false">
                        <span class="d-block d-sm-none"><i class="far fa-user"></i></span> <span class="d-none d-sm-block">Slider</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="ui-tabs-accordions.html#messages2" role="tab" aria-selected="false">
                        <span class="d-block d-sm-none"><i class="far fa-envelope"></i></span> <span class="d-none d-sm-block">Video</span>
                    </a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active p-3" id="home2" role="tabpanel">
                    <p class="mb-0">Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
                </div>
                <div class="tab-pane p-3" id="profile2" role="tabpanel">
                    <p class="mb-0">Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit.</p>
                </div>
                <div class="tab-pane p-3" id="messages2" role="tabpanel">
                    <p class="mb-0">Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.</p>
                </div>
            </div>
        </div>
    </div> -->

    <div class="row">
        <div class="col-xl-9 col-md-6 mb-4">
            <div class="card">
                <div class="card-body">
                    <div class="md-form mt-0 mb-0">
                        <input type="text" name="title" class="form-control" placeholder="Titel hier eingeben" value="">
                    </div>
                    <p id="permalink" class="mb-0 mt-2 d-none">Permalink: <a href="" target="_blank"></a> <button id="edit_permalink" type="button" class="btn btn-sm btn-secondary">Bearbeiten</button></p>
                    <input type="text" name="guid" class="form-control d-none" value="">

                    <p id="permalink_edit" class="mb-0 mt-2 d-none">Permalink: <?=$helper->getHost()?> <input type="text" name="name" class="form-control form-control-sm col-md-4 d-inline" value=""> / <button type="button"  id="save_permalink" class="btn btn-sm btn-secondary">Speichern</button></p>
                </div>
            </div>
            <div class="card">
                <div class="card-body p-0">
                    <textarea id="editor" class="mt-4" name="content" type="text"></textarea>
                </div>
            </div>
            <div class="card mt-4">
                <div class="card-body">
                    <label>Stichwörter</label>
                    <div class="md-form mt-0 mb-0">
                        <div class="chips chips-placeholder"></div>
                        <textarea type="text" name="keywords" class="d-none"></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card">
                <div class="card-body">
                    <p class="text-center h6-responsive">Veröffentlichen</p>
                    <select name="status" class="mdb-select colorful-select dropdown-primary">
                        <option value="publish">Veröffentlicht</option>
                        <option value="draft">Entwurf</option>
                    </select>
                    
                    <button type="submit" class="btn btn-primary float-right mt-3" id="add">Erstellen</button>
                </div>
            </div>

            <div class="card mt-4">
                <div class="card-body">
                    <p class="text-center h6-responsive">Beitragsbild</p>
                    <div id="uploadImage" class="md-form mb-0">
                        <div class="file-field">

                            <input type="file" id="fileupload_img" name="header_img" class="filestyle" data-input="false" data-buttonname="btn-secondary" tabindex="-1" style="position: absolute; clip: rect(0px, 0px, 0px, 0px);">
                            <div class="bootstrap-filestyle input-group">
                                <span class="group-span-filestyle " tabindex="0">
                                    <label for="fileupload_img" class="btn btn-secondary ">
                                        <span class="icon-span-filestyle fas fa-folder-open"></span> 
                                        <span class="buttonText">Datei wählen</span>
                                    </label>
                                </span>
                            </div>
                            <input name="file_name_img" type="text" class="d-none">
                        </div>
                    </div>
                    <div id="progress_img" class="progress d-none" style="margin-top: 20px;">
                        <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>

                    <table id="files_img" style="margin-top:0px;" class="files table d-none mb-0 table-responsive-lg table-borderless"></table>      
                </div>
            </div>
            <div class="card mt-4">
                <div class="card-body">
                    <p class="text-center h6-responsive">Seiten-Attribute</p>
                    <div>
                        <label>Seitentyp</label>
                        <select name="page_type" class="form-control select2">
                            <option value="page">Standart</option>
                            <?php
                            $page_types=$helper->getPageType();
                            if ($page_types!==false):
                                foreach($page_types as $page_type){
                                    ?>
                                    <option value="<?=$page_type->__get('name')?>"><?=$page_type->__get('title')?></option>
                                    <?php
                                }
                            endif;
                            ?>
                        </select>
                    </div>
                    <div class="mt-3">
                        <label>Kommentare</label>
                        <select name="comment_status" class="mdb-select colorful-select dropdown-primary">
                            <option value="open" selected>Erlaubt</option>
                            <option value="close">Nicht Erlaubt</option>
                        </select>
                    </div>
                    <div class="d-none">
                        <label>Reihenfolge</label>
                        <div class="md-form mt-0 mb-0">
                            <input type="number" name="menu_order" class="form-control" placeholder="Reihenfolge" value="0">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">

    $("#editor").summernote({
        lang:'de-DE',
        placeholder: 'Content Text',
        height: 300,
        minHeight: 200,
        maxHeight: 500,
        toolbar: [
            //[groupname,[list buttons]]
            ['insert',['picture','link','video','table']],
            ['style',['bold','italic','underline']],
            ['font', ['strikethrough', 'superscript', 'subscript']],
            ['fontsize', ['fontsize']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph','style']],
            ['height', ['height','codeview']],
            
        ],
    });
     
    $("#edit_permalink").on('click', function(){
        $("#permalink_edit").removeClass('d-none');
        $("#permalink").addClass('d-none');
    });

    $("#save_permalink").on('click', function(){
        var guid='<?=$helper->getHost()?>'+$("input[name=name]").val()+'/';
        $("input[name=guid]").val(guid);
        $("#permalink a").html(guid);
        $("#permalink a").attr('href', guid);
        $("#permalink_edit").addClass('d-none');
        $("#permalink").removeClass('d-none');
        checkName($("input[name=name]").val());
    });

    // Für Seite erstellen
    $('input[name=title]').on('change', function(){
        checkName();
    });  

    $('select[name=page_type]').on('change', function(){
        checkName();
    });
    
    var checkName=function(name=null){
        if (name!==null){
            var link = name;
        }
        else {
            var link = $('input[name=title]').val();
        }
        var url='<?=$helper->getHost()?>';          
        var page_type=$('select[name=page_type]').val();
        if (page_type==='page'){
            page_type='';
        }
        else page_type=page_type+'/';
                
        link=link.toLowerCase();
        link=link.replace(/ /g, "_");
        
        var request=$.ajax({
            url:'<?=$helper->getHost()?>api/checkName/',
            type:'POST',
            dataType:'JSON',
            data: {"name":link, 'page_type':$('select[name=page_type]').val()},
            success: function(result){
                console.log(result);
                $('#permalink a').attr('href',url+page_type+result.name+'/');
                $('#permalink a').html(url+page_type+result.name+'/');
                $('input[name=name]').val(result.name);
                $('input[name=guid]').val(url+page_type+result.name+'/');
                $('#permalink').removeClass('d-none');
            },
            error: function(xhr, status, error){
                alert(status + ': ' + error);
            }
        });
    };
    
    $('.chips-placeholder').material_chip({
        placeholder: '+ Stichwort',
        secondaryPlaceholder: '+ Stichwort',
    });
    
    $(document).on('submit', 'form', function(){
        // var content = document.querySelector('textarea[name=content]');
        // content.textContent = quill.container.firstChild.innerHTML;
        //content.textContent = editorElement.getData();        
        $('textarea[name=keywords]').val(JSON.stringify($('.chips').material_chip('data')));
        $('form').serialize();
        return true;
    });
</script>

<!-- Image Beitrag -->
<script>
    $('select').select2({ minimumResultsForSearch: -1 });

    /*jslint unparam: true, regexp: true */
    /*global window, $ */
    $(function () {
        'use strict';
        // Change this to the location of your server-side upload handler:
        var removeButton = $('<button/>')
                .addClass('btn btn-danger removeButton_img')
                .html('<i class="fa fa-trash"></i>')
                .attr('data-type','DELETE')
                .css({"float":"right"});

        $('#fileupload_img').fileupload({
            url: '/api/uploadImage/',
            dataType: 'json',
            autoUpload: true,
            acceptFileTypes: /(\.|\/)(jpe?g|bmp|png)$/i,
//                                    maxFileSize: 300000000,
            previewCrop: true,
            sequentialUploads: true,
            complete : function (data, e){
                // console.log(data);
                $('#progress_img .progress-bar').css('width','0%');
                $('#progress_img').addClass('d-none');
            }
        }).on('fileuploadstart', function (e) {
            $('#progress_img .progress-bar').css('width','0%');
            $('#progress_img').removeClass('d-none');
            $('#uploadImage').addClass('d-none');
        }).on('fileuploadprogress', function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('#progress_img .progress-bar').css(
                'width',
                progress + '%'
            );
        }).on('fileuploaddone', function (e, data) {
            data.context = $('#files_img');
            $.each(data.result.header_img, function (index, file) {
                if (file.error){
                    $('#window-modal .modal-title').html('<span class="text-danger">Ein Fehler ist aufgetreten</span>');
                    $('#window-modal .modal-body').html(file.error);
                    $('#window-modal .modal-footer').html('<button type="button" class="btn btn-danger" data-dismiss="modal">'+Close()+'</button>');
                    $('#window-modal').modal({
                        show:true,
                        backdrop:'static'
                    });
                }
                else {
                    var fileListe={};
                    var node = $('<div/>').attr({'class':'<?=$page_type==='video'?'mt-2 col-xl-6 col-lg-6':'mt-3 pl-0 pr-0 col-xl-12 col-lg-12'?> col-md-12 col-sm-12 col-12'});
                        node.append($('<img/>').attr({'src':'/source/upload/tmp_image/medium/'+file.name, 'class':'img-fluid img-thumbnail mb-2'}));
                    if (!index) {
                        node.append($('<div/>').attr({'class':'pb-0'}).append(removeButton.clone(true).data(data).attr('data-file', file.name)));
                    }
                    node.appendTo(data.context);

                    fileListe[file.name]=file.url;
                    $('#file_liste_img').val(JSON.stringify(fileListe));
                    $('#files_img').removeClass('d-none');
                    
                    $('input[name=file_name_img]').val(file.name);
                }
            });
            $('#progress_img').addClass('d-none');
        }).on('fileuploadfail', function (e, data) {
            $.each(data.files, function (index) {
                var error = $('<span class="text-danger"/>').text('File upload failed.');
                $(data.context.children()[index])
                    .append('<br>')
                    .append(error);
            });
        }).on('fileuploadprocessfail', function (e, data) {
            var errorMsg;

            // console.log(data);

            if (data.files[data.index].error=="File type not allowed"){
                errorMsg="Dateityp nicht erlaubt.";
            }
            else if (data.files[data.index].error=="File is too large"){
                errorMsg="Datei ist zu groß.";
            }
            else if (data.files[data.index].error=="Maximum number of files exceeded"){
                errorMsg="Maximale Anzahl der Dateien überschritten.";
            }
            else if (data.files[data.index].error=="File is too small"){
                errorMsg="Die Datei ist zu klein.";
            }
            else if (data.files[data.index].error=="Uploaded bytes exceed file size"){
                errorMsg="Hochgeladene Bytes überschreiten die Dateigröße.";
            }
            else {
                errorMsg="Ein Fehler ist aufgetreten.";
            }

            $('#window-modal .modal-title').html('<span class="text-danger">Ein Fehler ist aufgetreten</span>');
            $('#window-modal .modal-body').html(errorMsg);
            $('#window-modal .modal-footer').html('<button type="button" class="btn btn-danger" data-dismiss="modal">Schließen</button>');
            $('#window-modal').modal({
                show:true,
                backdrop:'static'
            });
        }).prop('disabled', !$.support.fileInput)
            .parent().addClass($.support.fileInput ? undefined : 'disabled');
    });
    
    
    $(document).on('click', '.removeButton_img', function(e){
        e.preventDefault();
        var url = '/api/uploadImage/',
            $this=$(this);
        $.ajax({
            url: url+'?header_im='+$(this).attr('data-file'),
            dataType: 'json',
            type: 'DELETE',
            success: function(data, xhr){
                var $td=$this.parent(),
                    $tr=$td.parent();
                var fileListe={};
                $.each(data, function (index, result) {
                    if (result){
                        $($tr).remove();
                        delete fileListe[index];
                        $('#file_liste_img').val(JSON.stringify(fileListe));
                    }
                    $('#files_img').addClass('d-none');
                });
                $('#uploadImage').removeClass('d-none');
            }
        });

    });    
</script>