<div class="content-center">
    <div class="content-desc-center">
        <div class="container">
            <div class="card mo-mt-2">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col-lg-4 offset-lg-1">
                            <div class="ex-page-content">
                                <h1 class="text-dark">Oops!</h1>
                                <p class="mb-5">
                                    Entschuldigung, es ist ein Fehler aufgetreten. Die angeforderte Template wurde nicht gefunden!
                                </p>
                                <a class="btn btn-primary mb-5 waves-effect waves-light" href="<?=$helper->getHost()?>dashboard/">
                                    <i class="mdi mdi-home"></i> Zurück zum Dashboard
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-5 offset-lg-1"><img src="<?=$helper->getHost()?>template/dashboard/asset/images/error.png" alt="" class="img-fluid mx-auto d-block"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>