<section id="main" class="row" style="margin: 0;">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="error-template" style="text-align: center;">
                    <h1>Oops!</h1>
                    <h2>Error</h2>
                    <div class="error-details">
                        Entschuldigung, es ist ein Fehler aufgetreten.
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>