<section class="mb-3">
    <div class="row">
        
        <style>
            tbody tr td.title{
                width:250px;
                line-height: 1.3;
                vertical-align: top;
                padding-top: 10px;
                font-weight: 600;
                font-size: 1rem;
            }

            tbody tr td {
                padding-bottom: 15px;
            }

            tbody tr td p {
                margin-bottom: 0px;
            }

            .select2-container{
                width: 130px!important;
            }
        </style>

        <?php
        if(isset($success) && $success===true){
            ?>
            <div class="col-lg-12 col-md-12">
                <div class="alert alert-success alert-dismissible fade show w-100" role="alert">
                    Einstellungen gespeichert.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <?php
        }
        ?>
        <div class="col-lg-12 col-md-12 mb-4">
            <div class="card">
                <div class="card-body pt-0 px-0">
                    <div class="card-body pb-0">
                        <form method="post" class="">
                            <table class="form" style="width:100%;">
                                <tbody>
                                    <tr>
                                        <td class="title" scope="row">
                                            Titel
                                        </td>
                                        <td>
                                            <input name="title" type="text" value="<?=$setting['title']?>" class="form-control">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="title" scope="row">
                                            Beschreibung
                                        </td>
                                        <td>
                                            <input name="description" type="text" value="<?=$setting['description']?>" class="form-control">
                                            <p class="description" id="tagline-description">Erkläre in ein paar Worten, worum es auf deiner Website geht.</p>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="title" scope="row">
                                            E-Mail-Adresse
                                        </td>
                                        <td>
                                            <input name="admin_email" type="email" value="<?=$setting['admin_email']?>" class="form-control">
                                            <p class="description">Diese Adresse wird für administrative Zwecke verwendet. 
                                                <!-- Wenn du diese änderst, bekommst du eine E-Mail an deine neue E-Mail-Adresse, um die Änderung zu bestätigen. Die neue Adresse wird erst nach dieser Bestätigung benutzt. --> </p>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="title" scope="row">
                                            Mitgliedschaft
                                        </td>
                                        <td> 
                                            <div class="custom-control custom-checkbox mt-2">
                                                <input name="users_can_register" type="checkbox" class="custom-control-input" id="users_can_register"> 
                                                <label class="custom-control-label" for="users_can_register">Jeder kann sich registrieren.</label>
                                            </div>
                                            <!-- <div class="form-check pl-0">
                                                <input name="users_can_register" type="checkbox" class="form-check-input" id="users_can_register" <?=$setting['users_can_register']==="0"?"":"checked"?> value="1">
                                                <label class="form-check-label" for="users_can_register" style="color:#212529;">Jeder kann sich registrieren.</label>
                                            </div> -->
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="title" scope="row">
                                            Standardrolle eines neuen Benutzers
                                        </td>
                                        <td>
                                            <select name="default_role">
                                                <option selected="selected" value="subscriber">Abonnent</option>
                                                <option value="contributor">Mitarbeiter</option>
                                                <option value="author">Autor</option>
                                                <option value="editor">Redakteur</option>
                                                <option value="administrator">Administrator</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="title" scope="row">Datumsformat</td>
                                        <td>
                                            <div class="custom-control custom-radio mt-2">
                                                <input name="date_format" type="radio" class="custom-control-input" id="date1" value="j. F Y" <?=$setting['date_format']==='j. F Y'?"checked":""?>> 
                                                <label class="custom-control-label" style="color:#212529;" for="date1">
                                                    <span class="date-time-text pr-2"><?=date("j. F Y")?></span> <code>j. F Y</code>
                                                </label>
                                            </div>

                                            <div class="custom-control custom-radio mt-2">
                                                <input name="date_format" type="radio" class="custom-control-input" id="date2" value="d.m.Y" <?=$setting['date_format']==='d.m.Y'?"checked":""?>> 
                                                <label class="custom-control-label" style="color:#212529;" for="date2">
                                                    <span class="date-time-text pr-2"><?=date("d.m.Y")?></span> <code>d.m.Y</code>
                                                </label>
                                            </div>

                                            
                                            <div class="custom-control custom-radio mt-2">
                                                <input name="date_format" type="radio" class="custom-control-input" id="date3" value="Y-m-d" <?=$setting['date_format']==='Y-m-d'?"checked":""?>> 
                                                <label class="custom-control-label" style="color:#212529;" for="date3">
                                                    <span class="date-time-text pr-2"><?=date("Y-m-d")?></span> <code>Y-m-d</code>
                                                </label>
                                            </div>

                                            <div class="custom-control custom-radio mt-2">
                                                <input name="date_format" type="radio" class="custom-control-input" id="date4" value="m/d/Y" <?=$setting['date_format']==='m/d/Y'?"checked":""?>> 
                                                <label class="custom-control-label" style="color:#212529;" for="date4">
                                                    <span class="date-time-text pr-2"><?=date("m/d/Y")?></span> <code>m/d/Y</code>
                                                </label>
                                            </div>

                                            <div class="custom-control custom-radio mt-2">
                                                <input name="date_format" type="radio" class="custom-control-input" id="date5" value="d/m/Y" <?=$setting['date_format']==='d/m/Y'?"checked":""?>> 
                                                <label class="custom-control-label" style="color:#212529;" for="date5">
                                                    <span class="date-time-text pr-2"><?=date("d/m/Y")?></span> <code>d/m/Y</code>
                                                </label>
                                            </div>
                                            
                                            <!-- 
                                            <p class="pl-1 mt-3" style="font-size: 1rem;">
                                                <strong>Vorschau:</strong> <span class="example"><?=date($setting['date_format'])?></span>
                                            </p> -->	
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="title" scope="row">
                                            Zeitformat
                                        </td>
                                        <td>

                                            <div class="custom-control custom-radio mt-2">
                                                <input name="time_format" type="radio" class="custom-control-input" id="time1" value="H:i" <?=$setting['time_format']==='H:i'?"checked":""?>> 
                                                <label class="custom-control-label" style="color:#212529;" for="time1">
                                                    <span class="date-time-text pr-2"><?=date("H:i")?></span> <code>H:i</code>
                                                </label>
                                            </div>

                                            <div class="custom-control custom-radio mt-2">
                                                <input name="time_format" type="radio" class="custom-control-input" id="time2" value="G:i" <?=$setting['time_format']==='G:i'?"checked":""?>> 
                                                <label class="custom-control-label" style="color:#212529;" for="time2">
                                                    <span class="date-time-text pr-2"><?=date("G:i")?></span> <code>G:i</code>
                                                </label>
                                            </div>
                                            <div class="custom-control custom-radio mt-2">
                                                <input name="time_format" type="radio" class="custom-control-input" id="time3" value="g:i a" <?=$setting['time_format']==='g:i a'?"checked":""?>> 
                                                <label class="custom-control-label" style="color:#212529;" for="time3">
                                                    <span class="date-time-text pr-2"><?=date("g:i a")?></span> <code>g:i a</code>
                                                </label>
                                            </div>
                                            
                                            <!--
                                            <p class="pl-1 mt-3" style="font-size: 1rem;">
                                                <strong>Vorschau:</strong> 
                                                <span class="example"><?=date($setting['time_format'])?></span>
                                                <span class="spinner"></span>
                                            </p> -->	
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="title" scope="row">
                                            Woche beginnt am
                                        </td>
                                        <td>
                                            <select name="start_of_week" id="start_of_week">
                                                <option value="0">Sonntag</option>
                                                <option value="1" selected="selected">Montag</option>
                                                <option value="2">Dienstag</option>
                                                <option value="3">Mittwoch</option>
                                                <option value="4">Donnerstag</option>
                                                <option value="5">Freitag</option>
                                                <option value="6">Samstag</option>
                                            </select>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <button type="submit" class="btn btn-primary mt-4">Änderungen speichern</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        
    </div>
</section>

<script>
    $('select').select2({ minimumResultsForSearch: -1 });
</script>