<section class="mb-3">
    <div class="row">
        
        <style>
            tbody tr td.title{
                width:250px;
                line-height: 1.3;
                vertical-align: top;
                padding-top: 10px;
                font-weight: 600;
                font-size: 1rem;
            }

            tbody tr td {
                padding-bottom: 15px;
            }

            tbody tr td p {
                margin-bottom: 0px;
            }

            .select2-container{
                width: 130px!important;
            }
        </style>

        <?php
        if(isset($success) && $success===true){
            ?>
            <div class="col-lg-12 col-md-12">
                <div class="alert alert-success alert-dismissible fade show w-100" role="alert">
                    Einstellungen gespeichert.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <?php
        }
        ?>
        <div class="col-lg-12 col-md-12 mb-4">
            <div class="card">
                <div class="card-body pt-0 px-0">
                    <div class="card-body pb-0">
                        
                        <form method="post" class="">
                            <table class="form" style="width:100%;">
                                <tbody>
                                    <tr id="transport">
                                        <td class="title" scope="row">
                                            Transport
                                        </td>
                                        <td>
                                            <select name="transport" class="mdb-select">
                                                <option value="smtp" <?=$setting['transport']==='smtp'?'selected':''?>>SMTP</option>
                                                <option value="sendmail" <?=$setting['transport']==='sendmail'?'selected':''?>>Sendmail</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr id="host">
                                        <td class="title" scope="row">
                                            Postausgang Server
                                        </td>
                                        <td>
                                            <input name="host" type="text" value="<?=$setting['host']?>" class="form-control">
                                        </td>
                                    </tr>
                                    <tr id="port">
                                        <td class="title" scope="row">
                                            Postausgang Port
                                        </td>
                                        <td>
                                            <input name="port" type="number" value="<?=$setting['port']?>" class="form-control">
                                        </td>
                                    </tr>
                                    <tr id="user">
                                        <td class="title" scope="row">
                                            Benutzername
                                        </td>
                                        <td> 
                                            <input name="user" type="text" value="<?=$setting['user']?>" class="form-control">
                                        </td>
                                    </tr>
                                    <tr id="password">
                                        <td class="title" scope="row">
                                            Passwort
                                        </td>
                                        <td> 
                                            <input name="password" type="password" value="<?=$setting['password']?>" class="form-control">
                                        </td>
                                    </tr>
                                    <tr id="mail_from">
                                        <td class="title" scope="row">
                                            Senden als
                                        </td>
                                        <td> 
                                            <input name="mail_from" type="email" value="<?=$setting['mail_from']?>" class="form-control">
                                        </td>
                                    </tr>
                                    <tr id="ssl">
                                        <td class="title" scope="row">
                                            Verschlüsselung
                                        </td>
                                        <td>
                                            <select name="ssl" class="mdb-select">
                                                <option value="ssl" <?=$setting['ssl']==='ssl'?'selected':''?>>SSL</option>
                                                <option value="tls" <?=$setting['ssl']==='tls'?'selected':''?>>TLS</option>
                                            </select>
                                        </td>
                                    </tr>
                                    
                                </tbody>
                            </table>
                            <button type="submit" class="btn btn-primary mt-4">Änderungen speichern</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $("select").select2({ minimumResultsForSearch: -1 });

    $(document).ready(function(){
        if ($("select[name=transport]").val()==='smtp'){
            $("#mail_from").addClass('d-none');
        }
        else {
            $("#host").addClass('d-none');
            $("#port").addClass('d-none');
            $("#user").addClass('d-none');
            $("#password").addClass('d-none');
            $("#ssl").addClass('d-none');
        }
    });


    $("select[name=transport]").on('change', function(){
        console.log($(this).val());
        if ($(this).val()==='smtp'){
            $("#host").removeClass('d-none');
            $("#port").removeClass('d-none');
            $("#user").removeClass('d-none');
            $("#password").removeClass('d-none');
            $("#ssl").removeClass('d-none');
            $("#mail_from").addClass('d-none');
        }
        else {
            $("#mail_from").removeClass('d-none');
            $("#host").addClass('d-none');
            $("#port").addClass('d-none');
            $("#user").addClass('d-none');
            $("#password").addClass('d-none');
            $("#ssl").addClass('d-none');
        }
    });

</script>