<section class="mb-3">
    <div class="row">
        <style>
            tbody tr td.title{
                width:250px;
                line-height: 1.3;
                vertical-align: top;
                padding-top: 10px;
                font-weight: 600;
                font-size: 1rem;
            }

            tbody tr td {
                padding-bottom: 15px;
            }

            tbody tr td p {
                margin-bottom: 0px;
            }
        </style>
        <?php
        if(isset($success) && $success===true){
            ?>
            <div class="col-lg-12 col-md-12">
                <div class="alert alert-success alert-dismissible fade show w-100" role="alert">
                    Einstellungen gespeichert.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <?php
        }
        ?>
        <div class="col-lg-12 col-md-12 mb-4">
            <div class="card">
                <div class="card-body pt-0 px-0">
                    <div class="card-body pb-0">
                        
                        <form method="post" class="">
                            <p>Die unten aufgeführten Größen bestimmen die maximalen Abmessungen in Pixel, die beim Hinzufügen von Bildern zur Mediathek verwendet werden.</p>
                            <table class="form">
                                <tbody>
                                    <tr>
                                        <td class="title" scope="row">Vorschaubilder</td>
                                        <td>
                                            <table class="form">
                                                <tbody>
                                                    <tr>
                                                        <td class="title" style="width:150px;" scope="row">Breite</td>
                                                        <td>
                                                            <input name="thumbnail_size_w" type="number" step="1" min="0" id="thumbnail_size_w" value="<?=$setting['thumbnail_size_w']?>" class="form-control">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td class="title" style="width:150px;" scope="row">Höhe</td>
                                                        <td>
                                                            <input name="thumbnail_size_h" type="number" step="1" min="0" id="thumbnail_size_h" value="<?=$setting['thumbnail_size_h']?>" class="form-control">
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>     
                                            <div class="custom-control custom-checkbox mt-2 mb-3">
                                                <input name="thumbnail_crop" type="checkbox" class="custom-control-input" id="thumbnail_crop" value="1" <?=$setting['thumbnail_crop']==="0"?"":"checked"?>> 
                                                <label class="custom-control-label" style="color:#212529;" for="thumbnail_crop">Das Vorschaubild auf die exakte Größe beschneiden (Vorschaubilder sind normalerweise proportional)</label>
                                            </div>                                       
                                            
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="title" scope="row">Mittelgroß</td>
                                        <td>
                                            <table class="form">
                                                <tbody>
                                                    <tr>
                                                        <td class="title" style="width:150px;" scope="row">Maximale Breite</td>
                                                        <td>
                                                            <input name="medium_size_w" type="number" step="1" min="0" id="medium_size_w" value="<?=$setting['medium_size_w']?>" class="form-control">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td class="title" style="width:150px;" scope="row">Maximale Höhe</td>
                                                        <td>
                                                            <input name="medium_size_h" type="number" step="1" min="0" id="medium_size_h" value="<?=$setting['medium_size_h']?>" class="form-control">
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="title" scope="row">Groß</td>
                                        <td>
                                            <table class="form">
                                                <tbody>
                                                    <tr>
                                                        <td class="title" style="width:150px;" scope="row">Maximale Breite</td>
                                                        <td>
                                                            <input name="large_size_w" type="number" step="1" min="0" id="large_size_w" value="<?=$setting['large_size_w']?>" class="form-control">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td class="title" style="width:150px;" scope="row">Maximale Höhe</td>
                                                        <td>
                                                            <input name="large_size_h" type="number" step="1" min="0" id="large_size_h" value="<?=$setting['large_size_h']?>" class="form-control">
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            <button type="submit" class="btn btn-primary mt-4">Änderungen speichern</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>