<form method="POST">
    <div class="row">
        <div class="col-xl-9 col-md-6 mb-4">
            <div class="card mb-4 processing d-none">
                <div class="card-body">
                    <div id="progress_convert" class="progress primary-color-dark mb-0 mt-o">
                        <div class="indeterminate"></div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="md-form mt-0 mb-0">
                        <input type="text" name="name" class="form-control" placeholder="Name hier eingeben" value="">
                    </div>
                </div>
            </div>
            
            <div class="card mt-4">
                <div class="card-body">
                    <div class="md-form mt-0 mb-0">
                        <input type="text" name="position" class="form-control" placeholder="Position hier eingeben" value="">
                    </div>
                    <div class="md-form mt-0 mb-0">
                        <input type="email" name="email" class="form-control" placeholder="E-Mail hier eingeben" value="">
                    </div>
                    <div class="md-form mt-0 mb-0">
                        <input type="text" name="phone" class="form-control" placeholder="Telefon hier eingeben" value="">
                    </div>
                </div>
            </div>

            <div class="card mt-4">
                <div class="card-body">
                    <div class="md-form mt-0 mb-0">
                        <input type="text" name="social[facebook]" class="form-control" placeholder="Facebook" value="">
                    </div>
                    <div class="md-form mt-0 mb-0">
                        <input type="text" name="social[instagram]" class="form-control" placeholder="Instagram" value="">
                    </div>
                    <div class="md-form mt-0 mb-0">
                        <input type="text" name="social[xing]" class="form-control" placeholder="XING" value="">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-md-6 mb-4">
            

            <div class="card">
                <div class="card-body">
                    <p class="text-center h6-responsive">Bild</p>
                    <div id="uploadImage" class="md-form mb-0">
                        <div class="file-field">
                            <div class="btn btn-primary btn-sm float-left">
                                <span>Datei wählen</span>
                                <input id="fileupload_img" name="header_img" type="file">
                                <input name="file_name_img" type="text" class="d-none">
                            </div>
                            <div class="file-path-wrapper">
                                <input class="file-path validate" type="text" placeholder="">
                            </div>
                        </div>
                    </div>
                    <div id="progress_img" class="progress d-none" style="margin-top: 20px;">
                        <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>

                    <table id="files_img" style="margin-top:0px;" class="files table d-none mb-0 table-responsive-lg table-borderless"></table>      
                </div>
            </div>


            <div class="card mt-4">
                <div class="card-body">
                    <p class="text-center h6-responsive">Veröffentlichen</p>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary float-right" id="add">Erstellen</button>
                </div>
            </div>

        </div>
    </div>
</form>

<!-- Image Beitrag -->
<script>
    /*jslint unparam: true, regexp: true */
    /*global window, $ */
    $(function () {
        'use strict';
        // Change this to the location of your server-side upload handler:
        var removeButton = $('<button/>')
                .addClass('btn btn-danger btn-sm removeButton_img')
                .html('<i class="fa fa-trash"></i>')
                .attr('data-type','DELETE')
                .css({"float":"right"});

        $('#fileupload_img').fileupload({
            url: '/api/uploadImage/',
            dataType: 'json',
            autoUpload: true,
            acceptFileTypes: /(\.|\/)(jpe?g|bmp|png)$/i,
//                                    maxFileSize: 300000000,
            previewCrop: true,
            sequentialUploads: true,
            complete : function (data, e){
                console.log(data);
                $('#progress_img .progress-bar').css('width','0%');
                $('#progress_img').addClass('d-none');
            }
        }).on('fileuploadstart', function (e) {
            $('#progress_img .progress-bar').css('width','0%');
            $('#progress_img').removeClass('d-none');
            $('#uploadImage').addClass('d-none');
        }).on('fileuploadprogress', function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('#progress_img .progress-bar').css(
                'width',
                progress + '%'
            );
        }).on('fileuploaddone', function (e, data) {
            data.context = $('#files_img');
            $.each(data.result.header_img, function (index, file) {
                if (file.error){
                    $('#window-modal .modal-title').html('<span class="text-danger">Ein Fehler ist aufgetreten</span>');
                    $('#window-modal .modal-body').html(file.error);
                    $('#window-modal .modal-footer').html('<button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">'+Close()+'</button>');
                    $('#window-modal').modal({
                        show:true,
                        backdrop:'static'
                    });
                }
                else {
                    var fileListe={};
                    var node = $('<div/>').attr({'class':'<?=$page_type==='video'?'mt-2 col-xl-6 col-lg-6':'mt-3 pl-0 pr-0 col-xl-12 col-lg-12'?> col-md-12 col-sm-12 col-12'});
                        node.append($('<img/>').attr({'src':'/source/upload/tmp_image/medium/'+file.name, 'class':'img-fluid img-thumbnail mb-2'}));
                    if (!index) {
                        node.append($('<div/>').attr({'class':'pb-0'}).append(removeButton.clone(true).data(data).attr('data-file', file.name)));
                    }
                    node.appendTo(data.context);

                    fileListe[file.name]=file.url;
                    $('#file_liste_img').val(JSON.stringify(fileListe));
                    $('#files_img').removeClass('d-none');
                    
                    $('input[name=file_name_img]').val(file.name);
                }
            });
            $('#progress_img').addClass('d-none');
        }).on('fileuploadfail', function (e, data) {
            $.each(data.files, function (index) {
                var error = $('<span class="text-danger"/>').text('File upload failed.');
                $(data.context.children()[index])
                    .append('<br>')
                    .append(error);
            });
        }).on('fileuploadprocessfail', function (e, data) {
            var errorMsg;

            console.log(data);

            if (data.files[data.index].error=="File type not allowed"){
                errorMsg="Dateityp nicht erlaubt.";
            }
            else if (data.files[data.index].error=="File is too large"){
                errorMsg="Datei ist zu groß.";
            }
            else if (data.files[data.index].error=="Maximum number of files exceeded"){
                errorMsg="Maximale Anzahl der Dateien überschritten.";
            }
            else if (data.files[data.index].error=="File is too small"){
                errorMsg="Die Datei ist zu klein.";
            }
            else if (data.files[data.index].error=="Uploaded bytes exceed file size"){
                errorMsg="Hochgeladene Bytes überschreiten die Dateigröße.";
            }
            else {
                errorMsg="Ein Fehler ist aufgetreten.";
            }

            $('#window-modal .modal-title').html('<span class="text-danger">Ein Fehler ist aufgetreten</span>');
            $('#window-modal .modal-body').html(errorMsg);
            $('#window-modal .modal-footer').html('<button type="button" class="btn btn-danger btn-sm" data-dismiss="modal">Schließen</button>');
            $('#window-modal').modal({
                show:true,
                backdrop:'static'
            });
        }).prop('disabled', !$.support.fileInput)
            .parent().addClass($.support.fileInput ? undefined : 'disabled');
    });
    
    
    $(document).on('click', '.removeButton_img', function(e){
        e.preventDefault();
        var url = '/api/uploadImage/',
            $this=$(this);
        $.ajax({
            url: url+'?header_im='+$(this).attr('data-file'),
            dataType: 'json',
            type: 'DELETE',
            success: function(data, xhr){
                var $td=$this.parent(),
                    $tr=$td.parent();
                var fileListe={};
                $.each(data, function (index, result) {
                    if (result){
                        $($tr).remove();
                        delete fileListe[index];
                        $('#file_liste_img').val(JSON.stringify(fileListe));
                    }
                    $('#files_img').addClass('d-none');
                });
                $('#uploadImage').removeClass('d-none');
            }
        });

    });    
</script>